### PR TITLE
Removes other races from being selectable.

### PR DESCRIPTION
**Pull request by mattroks101**
Only human and machine now.

### CODE REVIEW

**Comment by tigercat2000** [comment]
this won't actually work for any karma races, they'll still show up

**Comment by mattroks101** [comment]
I removed the whitelisted tag from whitelisted races, and tested it myself, they won't show up. Or at least they didn't when I tested it.

**Comment by Tastyfish** [comment]
We probably should remove the karma verbs and button too, unless we intend for that to be a thing.

**Comment by Pancakeflipper** [comment]
Agreed on that can we remove or disable the verbs for karma? remove perferably

**Pull request merged**
